//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEM5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEquipmentAccess
    {
        public int AccessID { get; set; }
        public int EmployeeID { get; set; }
        public string EquipmentName { get; set; }
        public Nullable<System.DateTime> AccessGrantedDate { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
