//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEM5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.MaterialQuantityHistory = new HashSet<MaterialQuantityHistory>();
            this.ProductMaterials = new HashSet<ProductMaterials>();
            this.WarehouseOperations = new HashSet<WarehouseOperations>();
        }
    
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public int SupplierID { get; set; }
        public Nullable<int> QuantityPerPackage { get; set; }
        public string Unit { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public Nullable<int> MinQuantity { get; set; }
        public Nullable<int> MaterialTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialQuantityHistory> MaterialQuantityHistory { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterials> ProductMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseOperations> WarehouseOperations { get; set; }
        public virtual MaterialTypes MaterialTypes { get; set; }
    }
}
