//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEM5.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEM5Entities : DbContext
    {
        public DEM5Entities()
            : base("name=DEM5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessCards> AccessCards { get; set; }
        public virtual DbSet<EmployeeEquipmentAccess> EmployeeEquipmentAccess { get; set; }
        public virtual DbSet<EmployeeMovements> EmployeeMovements { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Managers> Managers { get; set; }
        public virtual DbSet<MaterialQuantityHistory> MaterialQuantityHistory { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<MaterialTypes> MaterialTypes { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<PartnerSalesHistory> PartnerSalesHistory { get; set; }
        public virtual DbSet<PartnerSalesLocations> PartnerSalesLocations { get; set; }
        public virtual DbSet<PartnerTypes> PartnerTypes { get; set; }
        public virtual DbSet<ProductMaterials> ProductMaterials { get; set; }
        public virtual DbSet<ProductPriceHistory> ProductPriceHistory { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<WarehouseOperations> WarehouseOperations { get; set; }
    }
}
