//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEM5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerSalesLocations
    {
        public int SalesLocationID { get; set; }
        public int PartnerID { get; set; }
        public string LocationType { get; set; }
        public string LocationAddress { get; set; }
    
        public virtual Partners Partners { get; set; }
    }
}
