//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEM5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPriceHistory
    {
        public int PriceHistoryID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
