//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEM5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseOperations
    {
        public int OperationID { get; set; }
        public int MaterialID { get; set; }
        public System.DateTime OperationDate { get; set; }
        public string OperationType { get; set; }
        public int Quantity { get; set; }
    
        public virtual Materials Materials { get; set; }
    }
}
